INSERT INTO task_masters (dept, name, sub, special, requires_upload, is_mandatory) VALUES
('Sales', 'Upload PO', 'Customer PO + specs', 'sales', true, true),
('Sales', 'Confirm Dispatch Date', 'Received from Planning', 'dispatch', false, true),
('Design', 'BOM Upload', '', NULL, true, true),
('Design', 'Electrical Drawing', '', NULL, true, true),
('Design', 'Fabrication', '', NULL, true, true),
('Purchase', 'Enclosure', '', NULL, false, true),
('Purchase', 'Low Voltage Components', '', NULL, false, true),
('Purchase', 'Wire and Accessories', '', NULL, false, true),
('Purchase', 'Automation Components', '', NULL, false, true),
('Stores', 'Allocation of Material', '', NULL, false, true),
('Production', 'Assembly', '', NULL, false, true),
('Production', 'Material Receipt', '', NULL, false, true),
('Production', 'Wiring', '', NULL, false, true),
('QC', 'Receive Panel', 'Test & inspect', 'qc', false, true),
('QC', 'QC Decision', 'Pass → Dispatch | Fail → Rework/Redesign', 'qc', true, true),
('Dispatch', 'Ready for Dispatch', 'QC cleared panels', NULL, true, true),
('Accounts', 'Invoice & Dispatch Note', 'Billing & documentation', NULL, true, true);
